-- EJ 3.5 - Migración inicial (compatible con H2 y PostgreSQL)
CREATE TABLE sala (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(50)  NOT NULL UNIQUE,
    capacidad     INTEGER      NOT NULL,
    calle         VARCHAR(255),
    ciudad        VARCHAR(255),
    codigo_postal VARCHAR(255)
);

CREATE TABLE usuario (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email  VARCHAR(255) NOT NULL UNIQUE,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE reserva (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sala_id    BIGINT      NOT NULL REFERENCES sala (id),
    usuario_id BIGINT      NOT NULL REFERENCES usuario (id),
    inicio     TIMESTAMP   NOT NULL,
    fin        TIMESTAMP   NOT NULL,
    estado     VARCHAR(20) NOT NULL,
    version    BIGINT
);
