-- EJ 3.7 - Gobierno de superhéroes: órganos, gobiernos (uno por legislatura) y nombramientos
CREATE TABLE organo (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    tipo   VARCHAR(30)  NOT NULL,
    orden  INTEGER      NOT NULL
);

CREATE TABLE gobierno (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legislatura   INTEGER   NOT NULL UNIQUE,
    toma_posesion TIMESTAMP NOT NULL,
    cese          TIMESTAMP,
    vigente       BOOLEAN   NOT NULL
);

CREATE TABLE nombramiento (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gobierno_id BIGINT       NOT NULL REFERENCES gobierno (id),
    organo_id   BIGINT       NOT NULL REFERENCES organo (id),
    titular     VARCHAR(100) NOT NULL,
    CONSTRAINT uk_nombramiento_gobierno_organo UNIQUE (gobierno_id, organo_id)
);

INSERT INTO organo (nombre, tipo, orden) VALUES
    ('Presidencia del Gobierno',                                    'PRESIDENCIA',          1),
    ('Vicepresidencia Primera y de Asuntos Transversales',          'VICEPRESIDENCIA',      2),
    ('Vicepresidencia Segunda y de Sinergias',                      'VICEPRESIDENCIA',      3),
    ('Ministerio de Hacienda y Cuadre de Cuentas',                  'MINISTERIO',           4),
    ('Ministerio de Defensa contra Villanos',                       'MINISTERIO',           5),
    ('Ministerio de Superpoderes y Función Pública',                'MINISTERIO',           6),
    ('Ministerio de Capas, Mallas y Antifaces',                     'MINISTERIO',           7),
    ('Ministerio de Guaridas Secretas y Vivienda',                  'MINISTERIO',           8),
    ('Ministerio de Transformación Digital y Rayos Láser',          'MINISTERIO',           9),
    ('Ministerio de Kriptonita y Transición Ecológica',             'MINISTERIO',          10),
    ('Secretaría de Estado de Identidades Secretas',                'SECRETARIA_DE_ESTADO', 11),
    ('Secretaría de Estado de Onomatopeyas (¡Zas!, ¡Pum!, ¡Crash!)', 'SECRETARIA_DE_ESTADO', 12);

-- El gobierno de la primera legislatura, que es el que está en el poder al arrancar
INSERT INTO gobierno (legislatura, toma_posesion, cese, vigente) VALUES
    (1, TIMESTAMP '2024-01-01 12:00:00', NULL, TRUE);

INSERT INTO nombramiento (gobierno_id, organo_id, titular)
SELECT g.id, o.id, t.titular
FROM gobierno g
CROSS JOIN organo o
JOIN (VALUES
        (1,  'Vengador Holístico'),
        (2,  'Aguja Dinámico'),
        (3,  'Centella Transversal'),
        (4,  'Titán Presupuestario'),
        (5,  'Halcón Resiliente'),
        (6,  'Coloso Proactivo'),
        (7,  'Pantera Sostenible'),
        (8,  'Murciélago Inmobiliario'),
        (9,  'Relámpago Escalable'),
        (10, 'Meteoro Cuántico'),
        (11, 'Fantasma Omnicanal'),
        (12, 'Tornado Onomatopéyico')
     ) AS t (orden, titular) ON t.orden = o.orden
WHERE g.legislatura = 1;
