CREATE TABLE intervencion (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    fecha_hora    TIMESTAMP   NOT NULL,
    contenido     VARCHAR(255) NOT NULL    
);


INSERT INTO intervencion (fecha_hora, contenido) VALUES (TIMESTAMP '2024-01-01 12:00:00', 'El Vengador Holístico toma posesión como Presidente del Gobierno'),
    (TIMESTAMP '2024-01-02 09:30:00', 'El Halcón Resiliente presenta el plan de defensa contra villanos'),
    (TIMESTAMP '2024-01-03 14:15:00', 'El Coloso Proactivo anuncia la nueva estrategia de superpoderes'),
    (TIMESTAMP '2024-01-04 11:45:00', 'El Pantera Sostenible inaugura la primera guarida secreta ecológica'),
    (TIMESTAMP '2024-01-05 16:20:00', 'El Murciélago Inmobiliario firma un acuerdo para nuevas viviendas secretas');