spring.application.name=m6-integration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

atech.tarifas.url=http://localhost:${server.port:8080}/tarifas

logging.level.org.springframework.integration=info
