CREATE TABLE linea_pendiente (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id VARCHAR(20) NOT NULL,
    sala         VARCHAR(50) NOT NULL,
    fecha        DATE        NOT NULL,
    horas        INTEGER     NOT NULL,
    estado       VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
);
