spring.application.name=m2-reservas
spring.profiles.default=dev
# EJ 2.5 - Hilos virtuales (Java 21+): Tomcat, @Async, planificadores...
spring.threads.virtual.enabled=true
spring.jpa.open-in-view=false
spring.docker.compose.enabled=false

atech.reservas.salas=Turing,Lovelace,Hopper
atech.reservas.duracion-maxima=4h
atech.reservas.hora-apertura=8
atech.reservas.hora-cierre=20
atech.reservas.notificaciones.habilitadas=false

# EJ 2.4 - Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus,reservas
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true

info.app.nombre=${spring.application.name}
info.app.cliente=Atech Advanced Solutions
